### ISSUE TITLE
homie it wont let me change my contorls

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SuperTeamXP/FNF-Undertale-Web#1]

**Comment by LEVIXDDLMAO** [comment]
nvm im dumb

**Comment by SubtleXP** [comment]
Alright cool, enjoy!

**Comment by SubtleXP** [comment]
One thing I just don't hope happens, is those fnf unblocked websites steal this html5 port and don't give credit to me or the original creators

**Comment by LEVIXDDLMAO** [comment]
lol same here

**Comment by LEVIXDDLMAO** [comment]
I keeping getting suck at the dummy part

**Comment by SubtleXP** [comment]
WHAT?

**Comment by LEVIXDDLMAO** [comment]
>:D i get stuck in the wall

**Comment by LEVIXDDLMAO** [comment]
![Screenshot 2022-09-01 10 11 58 PM](https://user-images.githubusercontent.com/92174516/188057485-16573a83-fe65-4d89-80f6-f289bfb72911.png)

**Comment by SubtleXP** [comment]
Yo that's weird that didn't happen for me

**Comment by LEVIXDDLMAO** [comment]
lmao its fine ill just skip it

**Comment by LEVIXDDLMAO** [comment]
![Screenshot 2022-09-01 10 16 20 PM](https://user-images.githubusercontent.com/92174516/188057852-f2505cf7-b248-4170-81b2-44b15c907a4d.png)
okay i pull up

**Comment by LEVIXDDLMAO** [comment]
im done trying to play this
